# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PonMart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PonMart
  pod 'Charts', '~> 3.0.1'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
end
